language: android
sudo: false
android:
    components:
        - platform-tools
        - tools
        - build-tools-23.0.3
        - android-23
        - extra-android-m2repository
script:
    - cd BlinkIDDemo
    - ./gradlew clean :BlinkIDDemo:assembleRelease
    - ./gradlew clean :BlinkIDDemoCustomSegmentScan:assembleRelease
    - ./gradlew clean :BlinkIDDemoCustomUI:assembleRelease
    - ./gradlew clean :BlinkIDDetectorDemo:assembleRelease
    - ./gradlew clean :BlinkIDDirectApiDemo:assembleRelease
    - ./gradlew clean :BlinkIDRandomScanDemo:assembleRelease
