language: android
sudo: false
android:
    components:
        - platform-tools
        - tools
        - build-tools-23.0.3
        - android-23
        - extra-android-m2repository
script:
    - cd BlinkIDDemo
    - ulimit -s 1082768  # Require a bit of more memory.
    - ./gradlew clean assembleRelease
